### ISSUE TITLE
Walk before we run

### ISSUE THREAD

**Issue by oliverjam** [foundersandcoders/react-week#14]
I'm not sure trying to explain how React works internally before they students have even seen a component is the best idea. Talking about React elements and how JSX is transpiled isn't super helpful when you literally don't know what anything is.

We should pull most of that stuff out of the intro workshop and move it into further reading resources. For example it would probably be better for students to learn roughly how to use React, _then_ go and read this great blog post https://reactjs.org/blog/2015/12/18/react-components-elements-and-instances.html

If we switch to teaching hooks this would also be a great resource for some deeper background knowledge: https://overreacted.io/react-as-a-ui-runtime/

(thanks @vlbee for the link)

**Comment by astroash** [comment]
I’ve always liked the intro to react that this weeks takes. I think there’s a lot of new syntax when you first encounter react, and I think there’s value of taking some of the shock away by introducing jsx first.

**Comment by oliverjam** [comment]
Yeah I like it too but the last couple of React Weeks people have clearly been confused about the basics of defining and using components, passing props etc. Everyone always gets stuck on trying to call `ReactDOM.render()` multiple times and stuff too since that gets introduced before actual components.

I don't know, just feels like maybe we should have a more practical focus with the limited time we have and let them investigate the theoretical if they want to later.

I would definitely still want to keep the JSX intro, but maybe cut it down so it doesn't detract from learning what you actually need to know.

**Comment by mattlub** [comment]
Hi. Don't know whether this is still an issue but I'm strongly in support of this. We ran the schedule from this repo in April in Nazareth and I felt like there was much too much reading/theory before actually writing components and making things. React syntax is intentionally quite intuitive and readable- I think there should be a bigger focus on small projects/tasks involving writing components, as opposed to long reading workshops. 🤷‍♂ 

@oliverjam just giving my 2 cents, maybe it also runs differently in London or you've updated it. I'm happy to talk about possible changes if you think it's useful.

I also remember thinking the thing about using react simply with a script tag was great but maybe again was too much reading.

**Comment by oliverjam** [comment]
@mattlub I totally changed up the curriculum for FAC16 and made it much more focused on just writing components at first. You obviously still have to learn the basic API but (since it's hooks-focused) there's less of that to cover to.

The schedule should reflect the new intro structure: [Learn React](https://github.com/oliverjam/learn-react) first to learn the API, then [a workshop](https://github.com/oliverjam/react-food-workshop) where they write a whole bunch of stateful components.

**Comment by oliverjam** [comment]
So we can probably close this issue 😅
