### ISSUE TITLE
Workshop on `this`

### ISSUE THREAD

**Issue by oliverjam** [foundersandcoders/react-week#2]
`this` is confusing, especially when you start writing ES6 classes and have to figure out why you can't call `setState` of `undefined`...

We ideally need a morning challenge that introduces the concept of ensuring you know what your `this` is, and covers at least a few of the common ways you see `this` bound in React.

1. Inline arrow functions `onClick={() => this.setState({ ... })}`
1. Binding in the constructor `this.handleClick = this.handleClick.bind(this)` (ugh)
1. Class properties with arrow functions `handleClick = () => this.setState({ ... })` 🙌

**Comment by ZooeyMiller** [comment]
Gonna work on this this week 👍
