### ISSUE TITLE
Turn the Dynamic Data codealong into a workshop

### ISSUE THREAD

**Issue by oliverjam** [foundersandcoders/react-week#5]
Codealongs end up taking longer than planned, require a super-dedicated mentor who knows the material (usually has to be the person who wrote it), and still tend to end up with difficulties as people fall behind, make typos, lose track of what's happening, stop learning so they can frantically type to catch up etc.

We'd like to turn the [Dynamic Data](https://github.com/sofiapoh/react-dynamic-data-workshop) codealong into a workshop that can done in pairs over a couple of hours. The most important part of React week is getting everyone writing as much React as they can, getting used to the syntax, making the typos and easy mistakes that everyone makes at first. This is easier to achieve with actual workshops.

### Workshop

Build a Github profile card using the Github API. Learning outcomes:

1. Fetching external data
1. `componentDidMount`
1. Storing data in/rendering from state
1. Rendering a list with `array.map`
1. keys

**Comment by sofiapoh** [comment]
I'll start this week!
